[package]
name = "barn"
version = "0.1.0"
edition = "2021"

[dependencies]
# we're using the latest bevy and the agent should not change that
bevy = { git = "https://github.com/bevyengine/bevy" }
tracing = "0.1"
